# Generated by Django 5.1.2 on 2024-11-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('institution_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=100)),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('proprietor_name', models.CharField(blank=True, max_length=100)),
                ('letterhead', models.ImageField(blank=True, null=True, upload_to='letterheads/')),
            ],
        ),
    ]
