# Generated by Django 5.1.2 on 2024-11-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdata',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
