# Generated by Django 5.1.2 on 2024-11-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgenerator', '0002_pdfdata_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdata',
            name='excel',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
