# Generated by Django 5.1.2 on 2024-12-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgenerator', '0002_rename_institutionname_generatequotation_institution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatequotation',
            name='paragraph',
            field=models.CharField(blank=True, default='We are pleased to present the pricing for the specified items in your upcoming tender for a lab setups . Here is  the estimate for your Products required ', max_length=1000),
        ),
        migrations.AddField(
            model_name='generatequotation',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
