# Generated by Django 5.1.2 on 2025-01-02 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgenerator', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('Financial Docs', 'Financial Docs'), ('BOQ', 'BOQ'), ('Catalogue', 'Catalogue'), ('CE', 'CE'), ('ISO', 'ISO'), ('VAT', 'VAT')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='row_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
