# Generated by Django 5.1.2 on 2024-11-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgenerator', '0003_pdfdata_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdata',
            name='amount',
            field=models.FloatField(blank=True, max_length=50),
        ),
    ]
