# Generated by Django 5.1.2 on 2024-12-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generatequotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('paragraph', models.CharField(blank=True, default='We are pleased to present the pricing for the specified items in your upcoming tender for a lab setups . Here is  the estimate for your Products required ', max_length=1000)),
                ('notes', models.CharField(blank=True, default='Unit price shall include all custom duties and taxes, transportation cost tothe final destination and insurance cost.', max_length=200)),
                ('amount', models.FloatField(blank=True, max_length=50)),
                ('letterhead', models.ImageField(blank=True, null=True, upload_to='letterheads/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('excel', models.FileField(blank=True, null=True, upload_to='signatures/')),
            ],
        ),
        migrations.CreateModel(
            name='PDFData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('ourdesignation', models.CharField(blank=True, max_length=100)),
                ('institution_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('id_no', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('nameofcontract', models.CharField(blank=True, max_length=100)),
                ('amount', models.FloatField(blank=True, max_length=50)),
                ('days', models.DecimalField(blank=True, decimal_places=0, max_digits=50)),
                ('bidvaliditydays', models.DecimalField(blank=True, decimal_places=0, default=90, max_digits=50)),
                ('proprietor_name', models.CharField(blank=True, max_length=100)),
                ('attornity_name', models.CharField(blank=True, max_length=100)),
                ('attornity_designation', models.CharField(blank=True, max_length=100)),
                ('datedthis', models.CharField(blank=True, help_text='3 day of December 2024', max_length=100)),
                ('letterhead', models.ImageField(blank=True, null=True, upload_to='letterheads/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('attornitysign', models.ImageField(blank=True, null=True, upload_to='attornitysign/')),
                ('footer', models.ImageField(blank=True, null=True, upload_to='footer/')),
            ],
        ),
        migrations.CreateModel(
            name='priceschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionname', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, default='Unit price shall include all custom duties and taxes, transportation cost tothe final destination and insurance cost.', max_length=200)),
                ('amount', models.FloatField(blank=True, max_length=50)),
                ('letterhead', models.ImageField(blank=True, null=True, upload_to='letterheads/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('excel', models.FileField(blank=True, null=True, upload_to='signatures/')),
            ],
        ),
    ]
