# Generated by Django 5.1.2 on 2024-12-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templete2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdata',
            name='footer',
            field=models.ImageField(blank=True, null=True, upload_to='footer/'),
        ),
    ]
