# Generated by Django 5.1.2 on 2024-12-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templete2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatequotation',
            name='propritername',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
