# Generated by Django 5.1.2 on 2024-12-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templete2', '0002_pdfdata_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdata',
            name='attornity_designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pdfdata',
            name='attornity_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pdfdata',
            name='attornitysign',
            field=models.ImageField(blank=True, null=True, upload_to='attornitysign/'),
        ),
    ]
