# Generated by Django 5.1.2 on 2024-12-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templete2', '0002_generatequotation_propritername'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatequotation',
            name='terms1',
            field=models.CharField(blank=True, default='This Quotation is Valid for 4 weeks.', max_length=200),
        ),
        migrations.AddField(
            model_name='generatequotation',
            name='terms2',
            field=models.CharField(blank=True, default='Delivery Period: - Within 4 weeks after PO is confirmed. ', max_length=200),
        ),
        migrations.AddField(
            model_name='generatequotation',
            name='terms3',
            field=models.CharField(blank=True, default='Installation and Demonstration work is included. ', max_length=200),
        ),
        migrations.AddField(
            model_name='generatequotation',
            name='terms4',
            field=models.CharField(blank=True, default='Installation of the equipment’s will be done by our Engineers', max_length=200),
        ),
    ]
