# Generated by Django 5.1.2 on 2024-12-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templete2', '0003_pdfdata_attornity_designation_pdfdata_attornity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdata',
            name='bidvaliditydays',
            field=models.DecimalField(blank=True, decimal_places=0, default=90, max_digits=50),
        ),
        migrations.AddField(
            model_name='pdfdata',
            name='datedthis',
            field=models.CharField(blank=True, help_text='3 day of December 2024', max_length=100),
        ),
    ]
