# Generated by Django 5.1.2 on 2024-12-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templete2', '0004_pdfdata_bidvaliditydays_pdfdata_datedthis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdata',
            name='nameofcontract',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
